kurs=input("Kursunuzu daxil edin: ")
fakulte=input("Fakultenizi daxil edin:")
ad=input("Adinizi daxil edin: ")
soyad=input("Soyadinizi daxil edin: ")
print("Telebe "+ad+" "+soyad+" "+fakulte+"de "+kurs+"dur")
